# Configure Local Storage for CloudStack
---
- name: Ensure default local storage directory exists
  ansible.builtin.file:
    path: /var/lib/libvirt/images
    state: directory
    owner: "{{ prepare_kvm_local_storage_owner }}"
    group: "{{ prepare_kvm_local_storage_group }}"
    mode: "{{ prepare_kvm_local_storage_mode }}"

- name: Ensure MergeFS local storage directory exists
  ansible.builtin.file:
    path: "{{ prepare_kvm_mergefs_mount_point }}"
    state: directory
    owner: "{{ prepare_kvm_local_storage_owner }}"
    group: "{{ prepare_kvm_local_storage_group }}"
    mode: "{{ prepare_kvm_local_storage_mode }}"
  when: prepare_kvm_additional_storage | length > 0

- name: Configure local storage paths in agent.properties
  ansible.builtin.lineinfile:
    path: /etc/cloudstack/agent/agent.properties
    regexp: '^local\.storage\.path='
    line: "local.storage.path=/var/lib/libvirt/images,{{ prepare_kvm_mergefs_mount_point }}"
    create: false
  notify: Restart CloudStack Agent
  when: prepare_kvm_additional_storage | length > 0

- name: Configure local storage uuid list in agent.properties
  ansible.builtin.lineinfile:
    path: /etc/cloudstack/agent/agent.properties
    regexp: '^local\.storage\.uuid='
    line: "local.storage.uuid={{ prepare_kvm_local_storage_uuid_default }},{{ prepare_kvm_local_storage_uuid_mergefs }}"
    create: false
  notify: Restart CloudStack Agent
  when:
    - prepare_kvm_additional_storage | length > 0
    - prepare_kvm_local_storage_uuid_default | default('') | length > 0
    - prepare_kvm_local_storage_uuid_mergefs | default('') | length > 0
