# Kubernetes Cluster Role - Metadata (CloudStack CKS)
---
galaxy_info:
  author: Vikas Pogu
  description: Create Kubernetes clusters using CloudStack Kubernetes Service (CKS)
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

dependencies:
  - role: homelab.cloudstack.api_auth
