# Prepare KVM Role - Metadata
---
galaxy_info:
  author: CloudStack Operations Team
  description: Ansible role to prepare CloudStack KVM hypervisor hosts
  license: Apache-2.0

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - cloud
    - cloudstack
    - kvm
    - hypervisor
    - virtualization
    - libvirt

dependencies: []
