# Debian/Ubuntu specific variables for KVM Host
---
prepare_kvm_agent_packages:
  - cloudstack-agent

prepare_kvm_libvirt_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils

prepare_kvm_chrony_packages:
  - chrony

prepare_kvm_uefi_packages:
  - ovmf

prepare_kvm_aria2_packages:
  - aria2

prepare_kvm_libvirt_service: "libvirtd"
prepare_kvm_chrony_service: "chrony"

prepare_kvm_libvirtd_config_file: "/etc/libvirt/libvirtd.conf"
prepare_kvm_libvirt_config_file: "/etc/libvirt/libvirt.conf"
prepare_kvm_libvirtd_default_file: "/etc/default/libvirtd"
prepare_kvm_agent_properties_file: "/etc/cloudstack/agent/agent.properties"

prepare_kvm_repo_file: "/etc/apt/sources.list.d/cloudstack.list"
prepare_kvm_gpg_key_file: "/etc/apt/keyrings/cloudstack.gpg"

# Network configuration files
prepare_kvm_netplan_config_file: "/etc/netplan/60-cloudstack-bridges.yaml"
prepare_kvm_interfaces_config_file: "/etc/network/interfaces"

# AppArmor paths
prepare_kvm_apparmor_libvirtd_profile: "/etc/apparmor.d/usr.sbin.libvirtd"
prepare_kvm_apparmor_virt_aa_helper_profile: "/etc/apparmor.d/usr.lib.libvirt.virt-aa-helper"
prepare_kvm_apparmor_disable_dir: "/etc/apparmor.d/disable"
