# Debian/Ubuntu specific variables for Management Server
---
cloudstack_packages:
  - cloudstack-management

mysql_packages:
  - mysql-server

chrony_packages:
  - chrony

mysql_service: "mysql"
chrony_service: "chrony"

mysql_config_file: "/etc/mysql/my.cnf"
mysql_config_dir: "/etc/mysql/conf.d"

cloudstack_repo_file: "/etc/apt/sources.list.d/cloudstack.list"
cloudstack_gpg_key_file: "/etc/apt/keyrings/cloudstack.gpg"
