# API Auth Role - Metadata
---
galaxy_info:
  author: Vikas Pogu
  description: Common role for CloudStack API authentication and key management
  license: Apache-2.0

  min_ansible_version: '2.9'

  galaxy_tags:
    - cloud
    - cloudstack
    - api
    - authentication

dependencies: []
