# Prepare Management Role - Handlers
---
- name: Restart MySQL
  ansible.builtin.systemd:
    name: '{{ prepare_management_mysql_service }}'
    state: restarted
    daemon_reload: true

- name: Restart chrony
  ansible.builtin.systemd:
    name: '{{ prepare_management_chrony_service }}'
    state: restarted

- name: Restart CloudStack Management
  ansible.builtin.systemd:
    name: cloudstack-management
    state: restarted
    daemon_reload: true

- name: Reload nfs exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Restart nfs
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
