$ANSIBLE_VAULT;1.1;AES256
31306534623361616566323134613864303031636535366662303630626432333763613439663332
6638383131613639306434333338363837643234636461340a376334653234353466383033396631
65343331393634613532313731663733643364643337326137363534646464396236616237326336
6135653838633361650a613532333861653161383034626439653230353761303439396264616132
39396536353338356237323065663835383736336264313633376135366330393438656265343666
61633633343630393163366236613231646132356661616335656566343233306264363664326662
63316434363233333236313130303365336432666564643662336137656135323861376334663863
39343335666633393062373963353534643838663363396233333438663663653231633937396235
37373734303634353031313839363232633964636630376330346239346234336235386439343738
30633464613764336339316662306238353365623030333861343939663134633561393731313238
63623233646138623036363834343731323830346233363638363537383366633361306565323531
34613631333639353965373137353831613166303465663630383261393039636465626161316438
6235
