# Create CloudStack Clusters
---
- name: Create clusters
  ngine_io.cloudstack.cluster:
    api_url: "{{ cloudstack_api_url }}"
    api_key: "{{ cloudstack_api_key }}"
    api_secret: "{{ cloudstack_api_secret }}"
    name: "{{ cluster.name }}"
    zone: "{{ cloudstack_zone.name }}"
    pod: "{{ cluster.pod_name }}"
    hypervisor: "{{ cluster.hypervisor }}"
    cluster_type: "{{ cluster.cluster_type | default('CloudManaged') }}"
    state: present
    api_timeout: 300
  loop: "{{ cloudstack_clusters }}"
  loop_control:
    loop_var: cluster
  register: clusters_result

- name: Display cluster information
  ansible.builtin.debug:
    msg: "Cluster '{{ item.cluster.name }}' {{ 'created' if item.changed else 'already exists' }}"
  loop: "{{ clusters_result.results }}"
  when: clusters_result.results is defined
