# Instance Role - Metadata
---
galaxy_info:
  author: CloudStack Ops
  description: Create virtual machine instances using CloudStack API
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

dependencies:
  - role: api-auth

