# Cleanup Role - Metadata
---
galaxy_info:
  author: Vikas Pogu
  description: Ansible role to cleanup/uninstall CloudStack components
  license: Apache-2.0

  min_ansible_version: '2.9'

  galaxy_tags:
    - cloud
    - cloudstack
    - cleanup
    - uninstall

dependencies: []
