# Enable Zone at the end of configuration
---
- name: Enable zone
  ngine_io.cloudstack.zone:
    api_url: '{{ cloudstack_api_url }}'
    api_key: '{{ cloudstack_api_key }}'
    api_secret: '{{ cloudstack_api_secret }}'
    name: '{{ configure_zone_zone.name }}'
    state: enabled
