# Prepare Management Role - Metadata
---
galaxy_info:
  author: Vikas Pogu
  description: Ansible role to prepare CloudStack Management Server (MySQL, NFS, Management Server)
  license: Apache-2.0

  min_ansible_version: '2.9'

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - cloud
    - cloudstack
    - iaas
    - virtualization
    - database
    - mysql
    - management

dependencies: []
