# Configure Kubernetes Role - Metadata
---
galaxy_info:
  author: CloudStack Operations Team
  description: Ansible role to enable and configure CloudStack Kubernetes Service (CKS)
  license: Apache-2.0

  min_ansible_version: "2.9"

  galaxy_tags:
    - cloud
    - cloudstack
    - kubernetes
    - cks
    - containers

dependencies: []
